default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>
  username: <%= ENV["POSTGRES_USERNAME"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] || "admin_development" %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] || "admin_test" %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] || "admin_production" %>
